import { useCallback, useEffect, useState } from 'react';
import { api } from '../../utils/api';

const EMPTY = { name: '', email: '', from: '', isNed: false, order: '', photo: null };
export default function AdminReviewers() {
  const [reviewers, setReviewers] = useState([]); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); return api.adminGetReviewers().then(r => setReviewers(r.data)).catch(e => setMessage(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { load(); }, [load]);
  const set = (field, value) => setForm(current => ({ ...current, [field]: value }));
  const submit = async event => { event.preventDefault(); setSaving(true); setMessage(''); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => { if (key !== 'photo' || value) data.append(key, value); }); if (editing) await api.adminUpdateReviewer(editing.id, data); else await api.adminCreateReviewer(data); setForm(EMPTY); setEditing(null); setMessage('Reviewer saved.'); load(); } catch (e) { setMessage(e.message); } finally { setSaving(false); } };
  const edit = reviewer => { setEditing(reviewer); setForm({ name: reviewer.name, email: reviewer.email || '', from: reviewer.from || '', isNed: reviewer.isNed, order: reviewer.order || '', photo: null }); };
  const remove = async id => { if (!confirm('Delete this reviewer?')) return; try { await api.adminDeleteReviewer(id); load(); } catch (e) { setMessage(e.message); } };
  return <div className="p-6 lg:p-8 max-w-6xl mx-auto"><div className="mb-7"><div className="text-xs font-semibold uppercase tracking-widest mb-1" style={{ color: '#3E8B87' }}>Management</div><h1 className="text-2xl lg:text-3xl font-bold" style={{ color: '#1A2E38' }}>Reviewers</h1><p className="text-sm mt-2" style={{ color: '#7A9AA6' }}>Leave “From” empty for reviewers from NED University.</p></div>
    {message && <div className="mb-5 px-4 py-3 rounded-xl text-sm" style={{ background: 'rgba(62,139,135,0.09)', color: '#2D6E6A' }}>{message}</div>}
    <form onSubmit={submit} className="bg-white rounded-2xl border p-5 mb-7 grid grid-cols-1 sm:grid-cols-2 gap-4" style={{ borderColor: 'rgba(62,139,135,0.12)' }}>
      <label className="text-xs font-semibold" style={{ color: '#4A6472' }}>Name<input required value={form.name} onChange={e => set('name', e.target.value)} className="mt-1.5 w-full px-3 py-2.5 rounded-xl text-sm outline-none" style={{ border: '1.5px solid rgba(62,139,135,0.18)', background: '#FAFBFB', color: '#1A2E38' }} /></label>
      <label className="text-xs font-semibold" style={{ color: '#4A6472' }}>Email (optional)<input type="email" value={form.email} onChange={e => set('email', e.target.value)} className="mt-1.5 w-full px-3 py-2.5 rounded-xl text-sm outline-none" style={{ border: '1.5px solid rgba(62,139,135,0.18)', background: '#FAFBFB', color: '#1A2E38' }} /></label>
      <label className="text-xs font-semibold" style={{ color: '#4A6472' }}>From (optional)<input value={form.from} onChange={e => set('from', e.target.value)} placeholder="University or organization" className="mt-1.5 w-full px-3 py-2.5 rounded-xl text-sm outline-none" style={{ border: '1.5px solid rgba(62,139,135,0.18)', background: '#FAFBFB', color: '#1A2E38' }} /></label>
      <label className="text-xs font-semibold" style={{ color: '#4A6472' }}>Display order<input type="number" value={form.order} onChange={e => set('order', e.target.value)} className="mt-1.5 w-full px-3 py-2.5 rounded-xl text-sm outline-none" style={{ border: '1.5px solid rgba(62,139,135,0.18)', background: '#FAFBFB', color: '#1A2E38' }} /></label>
      <label className="text-xs font-semibold flex items-center gap-2 pt-5" style={{ color: '#4A6472' }}><input type="checkbox" checked={form.isNed} onChange={e => set('isNed', e.target.checked)} /> Reviewer from NED University</label>
      <label className="sm:col-span-2 text-xs font-semibold" style={{ color: '#4A6472' }}>Photo (optional)<input type="file" accept="image/png,image/jpeg" onChange={e => set('photo', e.target.files[0])} className="mt-1.5 w-full text-sm" /></label>
      <div className="sm:col-span-2 flex gap-3"><button className="px-4 py-2.5 rounded-xl text-sm font-semibold text-white" style={{ background: '#3E8B87' }} disabled={saving}>{saving ? 'Saving…' : editing ? 'Update reviewer' : 'Add reviewer'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(EMPTY); }} className="px-4 py-2.5 rounded-xl text-sm font-semibold">Cancel</button>}</div>
    </form>
    <div className="bg-white rounded-2xl border divide-y" style={{ borderColor: 'rgba(62,139,135,0.12)' }}>{reviewers.map(reviewer => <div key={reviewer.id} className="flex items-center gap-4 p-4">{reviewer.photo ? <img src={reviewer.photo} alt="" className="w-12 h-12 rounded-full object-cover" /> : <div className="w-12 h-12 rounded-full flex items-center justify-center" style={{ background: 'rgba(62,139,135,0.1)', color: '#3E8B87' }}>{reviewer.name.charAt(0)}</div>}<div className="flex-1 min-w-0"><p className="font-semibold" style={{ color: '#1A2E38' }}>{reviewer.name}</p><p className="text-xs" style={{ color: '#7A9AA6' }}>{reviewer.email || 'No email'}{reviewer.isNed ? ' · NED University' : reviewer.from ? ` · From: ${reviewer.from}` : ''}</p></div><button onClick={() => edit(reviewer)} className="text-sm font-semibold" style={{ color: '#3E8B87' }}>Edit</button><button onClick={() => remove(reviewer.id)} className="text-sm font-semibold text-red-500">Delete</button></div>)}{loading && <p className="p-8 text-center text-sm" style={{ color: '#7A9AA6' }}>Loading reviewers…</p>}{!loading && !reviewers.length && <p className="p-8 text-center text-sm" style={{ color: '#7A9AA6' }}>No reviewers added yet.</p>}</div>
  </div>;
}
